# Generated by Django 4.0.6 on 2022-08-02 02:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField()),
                ('timestamp', models.BigIntegerField()),
                ('duration', models.BigIntegerField()),
                ('event_count', models.IntegerField()),
                ('event_size', models.BigIntegerField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('kind', models.SmallIntegerField()),
                ('data', models.TextField(blank=True)),
                ('timestamp', models.BigIntegerField()),
                ('session_key', models.CharField(max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
